### ISSUE TITLE
Using Spring 4.0.5 (no spring boot) with spring-kafka 1.0.0 gives NoClassDefFoundError

### ISSUE THREAD

**Issue by jyoti-codes** [malwaredb/docker#17]
0

I have tried to use kafka with Spring version 4.0.5 without Spring Boot. I have used lowest version for Kafka since Spring version is also old and upgrading Spring right now is not possible

Below are newly added Maven dependency

 <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka-streams</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.kafka</groupId>
        <artifactId>spring-kafka</artifactId>
        <version>1.0.0.RELEASE</version>
    </dependency>
I callkafkaTemplate.send(message)within a scheduled Quartz job and getting

ERROR JobRunShell - Job DEFAULT.jobAlertSenderTask threw an unhandled Exception: java.lang.NoClassDefFoundError: org/springframework/util/concurrent/SettableListenableFuture at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:194) ~[spring-kafka-1.0.0.RELEASE.jar:na] at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:145) ~[spring-kafka-1.0.0.RELEASE.jar:na] at com.myProject.alertSender.kafka.KafkaMessageSender.send(KafkaMessageSender.java:60) ~[classes/:na]

**Comment by rjzak** [comment]
`NoClassDefFoundError` means that Java can't find a needed class. Since this project doesn't use Java, your error is somewhere else in your project, and not with this repo. This is just a Dockerfile for using Postgres with libraries for some similarity metrics pre-installed.
