### ISSUE TITLE
tomcat not able to load the jdbc driver even though jar is already present

### ISSUE THREAD

**Issue by jyoti-codes** [malwaredb/docker#2]
Caused by: java.lang.StackOverflowError: null
        at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:691) ~[na:1.8.0_382]
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579) ~[na:1.8.0_382]
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:271) ~[na:1.8.0_382]
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[na:1.8.0_382]
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135) ~[na:1.8.0_382]
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220) ~[na:1.8.0_382]
        at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_382]
        at java.util.logging.StreamHandler.publish(StreamHandler.java:224) ~[na:1.8.0_382]
        at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:116) ~[na:1.8.0_382]
        at java.util.logging.Logger.log(Logger.java:738) ~[na:1.8.0_382]
        at java.util.logging.Logger.doLog(Logger.java:765) ~[na:1.8.0_382]
        at java.util.logging.Logger.log(Logger.java:788) ~[na:1.8.0_382]
        at java.util.logging.Logger.warning(Logger.java:1477) ~[na:1.8.0_382]
        at com.impossibl.postgres.types.Registry.loadRaw(Registry.java:512) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.loadRaw(Registry.java:414) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.loadType(Registry.java:142) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.update(Registry.java:388) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.system.BasicContext.refreshSpecificType(BasicContext.java:379) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.system.BasicContext.refreshType(BasicContext.java:356) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.loadType(Registry.java:146) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.update(Registry.java:388) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.system.BasicContext.refreshSpecificType(BasicContext.java:379) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.system.BasicContext.refreshType(BasicContext.java:356) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.loadType(Registry.java:146) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.update(Registry.java:388) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.system.BasicContext.refreshSpecificType(BasicContext.java:379) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.system.BasicContext.refreshType(BasicContext.java:356) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.loadType(Registry.java:146) ~[pgjdbc-ng-0.7.jar:na]
        at com.impossibl.postgres.types.Registry.update(Registry.java:388) ~[pgjdbc-ng-0.7.jar:na]

**Comment by jyoti-codes** [comment]
I am using tomcat9 and postgres 14

**Comment by jyoti-codes** [comment]
version                                                                 
----------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
(1 row)

**Comment by rjzak** [comment]
Can you share a sample application? I wasn't aware that Java was installed, nor would be used with this Dockerfile. I'm happy to help to a point, but Java might be beyond the scope for this project.

**Comment by rjzak** [comment]
@jyoti-codes please try again and let me know if this is resolved, and close the issue if it works for you.
